### ISSUE TITLE
Versions-Abfrage in der updates.php

### ISSUE THREAD

**Issue by startef** [3UU/wordpress-shariff-wrapper#7]
Die Versionsabfrage für die Migration <1.7 und <1.9.4 macht im Moment für mich nicht so viel Sinn, weil du da auch auf version_compare() mit $code_version gewechselt bist. Damit wird aber die Migration _immer_ ausgeführt bei einer neuen Version, auch wenn die installierte bereits >1.7 ist. Hab ich da irgendwas übersehen? Eigentlich müsste es statt $code_version an der Stelle doch '1.7' bzw. '1.9.4' heißen.

**Comment by 3UU** [comment]
Hast Recht. Gefixt.
