### ISSUE TITLE
Facebook share: opened windows does not close after share

### ISSUE THREAD

**Issue by rob-st** [3UU/wordpress-shariff-wrapper#79]
Not sure if anyone else encountered this problem yet: If you share your article with facebook, the new window / tab opened for sharing it does _not_ close after the article has been shared to FB.

Changing in `shariff/services/shariff-facebook.php` line 13 from 
`$button_url = $service_url . '?u=' . $share_url;`
to
`$button_url = $service_url . '?=100&p[url]=' . $share_url;`
does close the window though. I found this _undocumented_ way of generating the URL on [stackoverflow](http://stackoverflow.com/a/30037299/1991146).

**Comment by startef** [comment]
Hi rob-st,

I wasn't able to reproduce the issue yet. Which Browser and OS did you use? Can you provide a link to page where this unintended behavior is shown?

Thanks for your help!

JP

**Comment by rob-st** [comment]
Hi JP,
sorry for the late response. It happens on Win 7 + 10 in Chrome, FF and Safari. Unfortunately I cannot give you a "misbehaving" example of this anymore, since I already "corrected" it by myself.

**Comment by 3UU** [comment]
close because done with recent version
