### ISSUE TITLE
restore_current_blog();

### ISSUE THREAD

**Issue by startef** [3UU/wordpress-shariff-wrapper#8]
Achtung: Deine neue Lösung funktioniert so nicht! Aber du hast recht, da ist ein Fehler und zwar eine falsche Klammer. Das restore_current_blog(); muss IN den Loop! So dass nach jedem Switch erst einmal wieder zurückgestellt wird, ansonsten läuft man in Probleme in der Linkgenerierung!

**Comment by startef** [comment]
switch_to_blog ist keine gute Idee, sondern es muss wirklich restore_current_blog() im loop sein, weil switch Daten in die globals schreibt. Kurzes Zitat:
If you view the source code for both functions you will see those functions push/pop data into a global called $GLOBALS['_wp_switched_stack']. If you do not call restore_current_blog() after every switch_to_blog(), $GLOBALS['_wp_switched_stack'] will be non-empty. If $GLOBALS['_wp_switched_stack'] is non-empty WP thinks it is in a switched mode, even if you switched back to the original blog using switch_to_blog(). The switched mode function is ms_is_switched() and it affects wp_upload_dir(). If wp_upload_dir() thinks it is in a switched mode, it can return data that is incorrect. wp_upload_dir() builds URLs for the site, so it is a very critical function.

**Comment by startef** [comment]
1.9.6 killt die Seite jetzt ganz mit einem PHP-Error. Ich hab dir nen PR gemacht. Bitte dringend fixen!

**Comment by 3UU** [comment]
restore_current_blog() sorgt bei mir in zwei WPMU-Blogs (Buddypress) dafuer, das zum Beispiel beim Moderieren der Kommentarte die Leute auf den falschen Blog redirectet werden. Da ist also auch was schraeg.

**Comment by startef** [comment]
Hast du denn auch die aktuelle Version getestet mit dem restore im Loop und nicht außerhalb?

**Comment by 3UU** [comment]
Egal, jetzt funktioniert es.
