### ISSUE TITLE
Mobile Icons are shown but quickly disappear

### ISSUE THREAD

**Issue by DieQuelle** [3UU/wordpress-shariff-wrapper#80]
Hello Guys,

thanks for your awesome Plugin.

I got one Problem with it, on desktop machines (my Browser is Chrome)

I see the Whatsapp and Threema Logo really quick, but after like 1sec I see them disappear.

This is a bit confusing for the user I think. So maybe you could add an fix to this which checks at first if the user is mobile/tablet or desktop.

Thanks

**Comment by startef** [comment]
Hi DieQuelle,

have you tried the option "Hide buttons until page is fully loaded." on the design tab in the Shariff settings?

Cheers
JP

**Comment by 3UU** [comment]
close because done with recent version
