### ISSUE TITLE
Bug in verbindung mit DIV / alignleft/right

### ISSUE THREAD

**Issue by WulfmanGer** [3UU/wordpress-shariff-wrapper#81]
Hi

ich nutze neben Wordpress noch Piwigo und lasse von dort in Wordpress Bilder anzeigen. Daher hab ich den folgenden Fehler auch erst beim Wordpress, Piwigo2Img und dem Theme gesucht. Der Piwigo2Img-Autor hat mir dann aber die Lösung gezeigt und das Problem bei dem Shariff-Wrapper gefunden.

https://www.platzeck.net/2016/12/15/testbeitrag/
Wie man sieht sind die Social-Buttons rechts angeordnet - statt drunter (zudem ging der Schrifzug "Twitter" verloren). Auf anderen Content-Seiten klappt das hingen mit drunter. Die Bilder werden hier mit Wordpress-Standardfunktionen angezeigt (das Piwigo-Plugin erstellt nur einfügbaren html-Code). Das Problem besteht nur bei Bildern mit class="wp-caption alignleft" und .right. Center ist kein Problem (nutze ich mit PiwigoPress schon länger ohne Probleme) - bzw. zumindest nicht aufgefallen.

Der Autor von Piwigo2Img hat mir unter http://piwigo.org/forum/viewtopic.php?pid=165573#p165573 das Problem ermittelt, erklärt und die Lösung genannt;

Ich muss in der shariff.min.css bzw. shariff.css (unterschied?! genutzt wird die min....) folgendes ergänzen:

.shariff-main {
    clear: both;
}

Hab ich gemacht - Klappt! (aktuell zu Demo-Zwecken entfernt!)

Wäre super wenn du dir das Thema mal anschaust und das mit der nächsten Version fixt ... :) Werde das zwar in der CSS schreiben, aber mit den nächsten update ist es ja sonst weg ;)

Danke
Wulfman

**Comment by 3UU** [comment]
Ohje, CSS ;-) Danke fuer den Hinweis. Ich werde mal JP bitten, das auf Seiteneffekte zu checken. Damit Du "updatesicher" bist, solltest DU fuer sowas aber auch die Otion nutzen koennen, selber CSS in den Container um die Shariff-Buttons zu schreiben. Die landen in Deiner WP-Datenbank und werden daher beim Update nicht ueberschrieben. Da bietet WP 4.7 jetzt aber ein paar Aenderungen, die fuer uns vielleicht auch ganz nuetzlich sein werden. Muss ich mir in Ruhe ansehen. Insofern kann es mit dem naechsten Update auch was dauern.

**Comment by WulfmanGer** [comment]
Danke :)

Hab jetzt unter den Shariff-Einstellungen unter "Individuelle CSS-Attribute für den Container um Shariff:"

clear:both;

stehen. Sieht sauber aus ;)

Dann warte ich mal die nächsten Updates ab und lese die Änderugnen - wenn das Problem gefixt ist, nehme ich das wieder raus ;)

Danke

**Comment by 3UU** [comment]
close because done with recent version
