### ISSUE TITLE
Remove HTML Tags from title for sharing

### ISSUE THREAD

**Issue by Zodiac1978** [3UU/wordpress-shariff-wrapper#82]
WordPress allows to use HTML tags in post titles, so the generated Tweet text for example will contain HTML, which is not correct.

![twitter-tag-problem](https://cloud.githubusercontent.com/assets/870475/25067160/27198044-223b-11e7-8a32-036da2f417d1.png)

See this post for more details of my workaround:
http://torstenlandsiedel.de/2017/01/13/html-tags-aus-shariff-wrapper-entfernen/ (German)

**Comment by startef** [comment]
Already on my list for the next release. :)

**Comment by 3UU** [comment]
close because done with recent version
