### ISSUE TITLE
Add a "Connect" widget

### ISSUE THREAD

**Issue by bviefhues** [3UU/wordpress-shariff-wrapper#83]
Feature request:

Add an additional "Connect" sidebar widget for links to your own social media profiles, mailto and RSS feed.

The connect widget should be independently configurable, with potentially different or other services than the sharing config, different order of services, with potentially different icon design, orientation, ...

This would help to maintain a consistent look and feel for the site, since the same icons and layout can be used for sharing and connect.

See http://nfvblog.net for an example. I created the sidebar social links by scraping the HTML generated by shariff-wrapper, modifying the links and putting the HTML in a sidebar text box.

**Comment by 3UU** [comment]
close because done with recent version
