### ISSUE TITLE
Missing rel="noopener" on shariff buttons with target="_blank"

### ISSUE THREAD

**Issue by NormanHoehne** [3UU/wordpress-shariff-wrapper#94]
Dear team,

since shariff is using links with target="_blank" you should add `rel="noopener"` for all of those links that open in a new window to improve security and performance.

Please take a look at:

- https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
- https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/

Chrome has fixed this vulnerability long time a go, but e.g. firefox is still vulnerable.

Cheers,
Norman

**Comment by 3UU** [comment]
done in 4.5.3

**Comment by Jolle775** [comment]
Dear Team, this is still an issue. 

![Bildschirmfoto 2023-09-12 um 17 36 22](https://github.com/3UU/wordpress-shariff-wrapper/assets/26974185/ad8b3b63-b203-4cb5-b305-f1befd509927)
